# Build the strapi image
steps:
  - name: 'gcr.io/cloud-builders/docker'
    args:
      [
        'build',
        '-t',
        'gcr.io/$PROJECT_ID/$_SERVICE_NAME/$SHORT_SHA',
        './docker/angular.dockerfile'
      ]

  # push the container image to Container Registry
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/$PROJECT_ID/$_SERVICE_NAME']

  ### Deploy container image to Cloud Run

  - name: 'gcr.io/cloud-builders/gcloud'
    args:
      - 'run'
      - 'deploy'
      - '$_SERVICE_NAME'
      - '--image'
      - 'gcr.io/$PROJECT_ID/$_SERVICE_NAME'
      - '--region'
      - '$_DEPLOY_REGION'
      - '--platform'
      - 'managed'
      - '$PROJECT_ID'
      - '--project'
      - '$PROJECT_ID'

substitutions:
  _OUTPUT_DIST_PATH: '/'
  _DEPLOY_PROJECT: ''
  _SERVICE_NAME: ''
  _REGION: ''

timeout: 2700s
