export enum ETypesComponentStrapi {
  class = 'pagina_turma.midia',
  classPUT = 'pagina_turma',
  registersPUT = 'registro',
  intro = 'introducao',
  registers = 'registros.midia',
  registersText = 'registros.texto',
  paginas_aulas = 'paginas.aulas',
  paginas_imagem = 'paginas.imagem',
  paginas_footer = 'paginas.footer',
  professor = 'professor',
  photo = 'foto',
  serie = 'serie',
  series = 'series',
  professor_book = 'livro_professors',
}
